
# 优先级从上往下开始检查，权限节点是 xlr.chat.名称，玩家默认拥有 xlr.chat.default 权限
# 聊天格式顺序 [前缀] [玩家名称] : [16进制颜色] [聊天内容]
# 可多个聊天格式，格式名称可自定义
Chat:
  op: "&a%player%: %color1%%chat%"
  default: "&a%player%: &a%chat%"

# 16进制渐变颜色变量配置，可以创建多个
# 可以在上面使用变量是 %color1% %color2%
Variable:
  color1: "#e4afcb-#7edbdc"
  color2: "#e4afcb-#eef1f5"
  color3: "#00c6fb-#005bea"
