name: XLRHopper
version: 1.3.0
main: xlingran.Shan
api-version: 1.21.1
author: Shan
description: 高级漏斗传输插件

commands:
  xlrhopper:
    description: XLRHopper 漏斗模板
    usage: /xlrhopper <mode|create mode <名称>|edit mode <名称>|give <玩家|%player%> <等级> [数量]|reload>

permissions:
  xlrhopper.admin:
    description: 重载插件配置（reload）
    default: op
  xlrhopper.create.mode:
    description: 创建过滤模板 (create mode)
    default: op
  xlrhopper.edit.mode:
    description: 编辑已有过滤模板 (edit mode)
    default: op
  xlrhopper.mode:
    description: 打开漏斗模板列表 (mode)
    default: op
  xlrhopper.give:
    description: 给予等级漏斗 (give)
    default: op
