package xlingran;

import org.bukkit.Material;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 对 switch 未覆盖的材质，按英文 ID 词素组合中文名（如 REDSTONE_BLOCK → 红石块）。
 */
final class ItemNamesZhCompose {

    private static final Map<String, String> TOKENS = new HashMap<>();
    private static final Map<String, String> SUFFIXES = new HashMap<>();

    static {
        initTokens();
        initSuffixes();
    }

    private ItemNamesZhCompose() {
    }

    static String compose(Material material) {
        return compose(material.name());
    }

    static String compose(String enumName) {
        if (enumName == null || enumName.isEmpty()) {
            return null;
        }
        List<String> parts = List.of(enumName.split("_"));
        StringBuilder result = new StringBuilder();
        int index = 0;
        while (index < parts.size()) {
            boolean matched = false;
            int maxLen = Math.min(4, parts.size() - index);
            for (int len = maxLen; len >= 1; len--) {
                String segment = String.join("_", parts.subList(index, index + len));
                if (index + len == parts.size() && SUFFIXES.containsKey(segment)) {
                    result.append(SUFFIXES.get(segment));
                    index += len;
                    matched = true;
                    break;
                }
                String token = TOKENS.get(segment);
                if (token != null) {
                    result.append(token);
                    index += len;
                    matched = true;
                    break;
                }
            }
            if (!matched) {
                return null;
            }
        }
        return result.isEmpty() ? null : result.toString();
    }

    private static void initSuffixes() {
        putSuffix("BLOCK", "块");
        putSuffix("ORE", "矿石");
        putSuffix("INGOT", "锭");
        putSuffix("NUGGET", "粒");
        putSuffix("SEEDS", "种子");
        putSuffix("SAPLING", "树苗");
        putSuffix("LOG", "原木");
        putSuffix("WOOD", "木");
        putSuffix("STEM", "柄");
        putSuffix("HYPHAE", "菌核");
        putSuffix("PLANKS", "木板");
        putSuffix("STAIRS", "楼梯");
        putSuffix("SLAB", "台阶");
        putSuffix("WALL", "墙");
        putSuffix("FENCE", "栅栏");
        putSuffix("GATE", "门");
        putSuffix("DOOR", "门");
        putSuffix("TRAPDOOR", "活板门");
        putSuffix("BUTTON", "按钮");
        putSuffix("PLATE", "板");
        putSuffix("PRESSURE_PLATE", "压力板");
        putSuffix("BRICKS", "砖");
        putSuffix("BRICK", "砖");
        putSuffix("SHARD", "碎片");
        putSuffix("CLUSTER", "簇");
        putSuffix("CRYSTAL", "水晶");
        putSuffix("TORCH", "火把");
        putSuffix("LANTERN", "灯笼");
        putSuffix("CARPET", "地毯");
        putSuffix("BANNER", "旗帜");
        putSuffix("BED", "床");
        putSuffix("BOAT", "船");
        putSuffix("CHEST", "箱子");
        putSuffix("SHULKER_BOX", "潜影盒");
        putSuffix("BUNDLE", "捆包");
        putSuffix("BUCKET", "桶");
        putSuffix("SPAWN_EGG", "刷怪蛋");
        putSuffix("MINECART", "矿车");
        putSuffix("RAIL", "铁轨");
        putSuffix("CANDLE", "蜡烛");
        putSuffix("SIGN", "告示牌");
        putSuffix("HANGING_SIGN", "悬挂告示牌");
        putSuffix("POT", "罐");
        putSuffix("SKULL", "头颅");
        putSuffix("HEAD", "头颅");
        putSuffix("WOOL", "羊毛");
        putSuffix("CARPET", "地毯");
        putSuffix("CONCRETE", "混凝土");
        putSuffix("POWDER", "粉末");
        putSuffix("GLASS", "玻璃");
        putSuffix("PANES", "板");
        putSuffix("PANE", "板");
        putSuffix("LEAVES", "树叶");
        putSuffix("ROOTS", "根");
        putSuffix("VINES", "藤");
        putSuffix("CORAL", "珊瑚");
        putSuffix("CORAL_BLOCK", "珊瑚块");
        putSuffix("CORAL_FAN", "珊瑚扇");
        putSuffix("FAN", "扇");
        putSuffix("BLOCK", "块");
        putSuffix("BULB", "灯泡");
        putSuffix("LAMP", "灯");
        putSuffix("ROD", "杆");
        putSuffix("SHELF", "架");
        putSuffix("BOOKSHELF", "书架");
        putSuffix("ANVIL", "砧");
        putSuffix("STATION", "台");
        putSuffix("TABLE", "台");
        putSuffix("FURNACE", "炉");
        putSuffix("SMOKER", "烟熏炉");
        putSuffix("BLAST_FURNACE", "高炉");
        putSuffix("GRINDSTONE", "砂轮");
        putSuffix("STONECUTTER", "切石机");
        putSuffix("SMITHING", "锻造");
        putSuffix("TEMPLATE", "模板");
        putSuffix("TRIM", "纹饰");
        putSuffix("ARMOR", "盔甲");
        putSuffix("SWORD", "剑");
        putSuffix("PICKAXE", "镐");
        putSuffix("AXE", "斧");
        putSuffix("SHOVEL", "锹");
        putSuffix("HOE", "锄");
        putSuffix("HELMET", "头盔");
        putSuffix("CHESTPLATE", "胸甲");
        putSuffix("LEGGINGS", "护腿");
        putSuffix("BOOTS", "靴子");
        putSuffix("HORSE_ARMOR", "马铠");
        putSuffix("BANNER_PATTERN", "旗帜图案");
        putSuffix("DISC", "唱片");
        putSuffix("FRAGMENT", "碎片");
        putSuffix("POD", "荚");
        putSuffix("CROP", "作物");
        putSuffix("BERRIES", "浆果");
        putSuffix("FUNGUS", "菌");
        putSuffix("NYLIUM", "菌岩");
        putSuffix("WART", "疣");
        putSuffix("STEM", "柄");
        putSuffix("MUSHROOM", "蘑菇");
        putSuffix("MUSHROOM_BLOCK", "蘑菇块");
    }

    private static void initTokens() {
        // 修饰 / 产地
        putToken("DEEPSLATE", "深层");
        putToken("NETHER", "下界");
        putToken("END", "末地");
        putToken("STRIPPED", "去皮");
        putToken("POLISHED", "磨制");
        putToken("CHISELED", "雕纹");
        putToken("CRACKED", "裂纹");
        putToken("MOSSY", "苔藓");
        putToken("WARPED", "诡异");
        putToken("CRIMSON", "绯红");
        putToken("SOUL", "灵魂");
        putToken("RAW", "粗");
        putToken("REINFORCED", "强化");
        putToken("WEATHERED", "风化");
        putToken("EXPOSED", "斑驳");
        putToken("OXIDIZED", "氧化");
        putToken("WAXED", "涂蜡");
        putToken("CUT", "切制");
        putToken("SMOOTH", "平滑");
        putToken("INFESTED", "虫蚀");
        putToken("POTTED", "盆栽");
        putToken("DYED", "染色");
        putToken("LIGHT", "淡");
        putToken("BLUE", "蓝");
        putToken("BLACK", "黑");
        putToken("WHITE", "白");
        putToken("RED", "红");
        putToken("YELLOW", "黄");
        putToken("GREEN", "绿");
        putToken("BROWN", "棕");
        putToken("PURPLE", "紫");
        putToken("CYAN", "青");
        putToken("GRAY", "灰");
        putToken("GREY", "灰");
        putToken("PINK", "粉");
        putToken("ORANGE", "橙");
        putToken("MAGENTA", "品红");
        putToken("LIME", "黄绿");

        // 基础材质 / 自然
        putToken("STONE", "石头");
        putToken("GRANITE", "花岗岩");
        putToken("DIORITE", "闪长岩");
        putToken("ANDESITE", "安山岩");
        putToken("DEEPSLATE", "深层");
        putToken("CALCITE", "方解石");
        putToken("TUFF", "凝灰岩");
        putToken("DRIPSTONE", "滴水石");
        putToken("POINTED", "尖");
        putToken("MOSS", "苔藓");
        putToken("MUD", "泥巴");
        putToken("PACKED", "压实");
        putToken("ROOTED", "缠根");
        putToken("SCULK", "幽匿");
        putToken("CATALYST", "催发体");
        putToken("SHRIEKER", "尖啸体");
        putToken("SENSOR", "传感器");
        putToken("VEIN", "脉络");
        putToken("GRASS", "草");
        putToken("DIRT", "泥土");
        putToken("COARSE", "砂土");
        putToken("PODZOL", "灰化土");
        putToken("MYCELIUM", "菌丝");
        putToken("FARMLAND", "耕地");
        putToken("SAND", "沙");
        putToken("GRAVEL", "沙砾");
        putToken("CLAY", "黏土");
        putToken("TERRACOTTA", "陶瓦");
        putToken("GLAZED", "带釉");
        putToken("ICE", "冰");
        putToken("SNOW", "雪");
        putToken("POWDER", "粉末");
        putToken("OBSIDIAN", "黑曜石");
        putToken("CRYING", "哭泣");
        putToken("MAGMA", "岩浆");
        putToken("BASALT", "玄武岩");
        putToken("BLACKSTONE", "黑石");
        putToken("GILDED", "镶金");
        putToken("QUARTZ", "石英");
        putToken("AMETHYST", "紫水晶");
        putToken("BUDDING", "芽");
        putToken("BUD", "芽");
        putToken("ECHO", "回响");
        putToken("SUSPICIOUS", "可疑");
        putToken("RECOVERY", "追溯");
        putToken("COMPASS", "指南针");
        putToken("SPYGLASS", "望远镜");
        putToken("GOAT", "山羊");
        putToken("HORN", "角");

        // 木 / 竹 / 植物
        putToken("OAK", "橡木");
        putToken("SPRUCE", "云杉");
        putToken("BIRCH", "白桦");
        putToken("JUNGLE", "丛林");
        putToken("ACACIA", "金合欢");
        putToken("DARK", "深色");
        putToken("MANGROVE", "红树");
        putToken("CHERRY", "樱花");
        putToken("BAMBOO", "竹子");
        putToken("MOSAIC", "马赛克");
        putToken("AZALEA", "杜鹃");
        putToken("FLOWERING", "盛开");
        putToken("BIG", "大型");
        putToken("SMALL", "小型");
        putToken("DEAD", "枯");
        putToken("SEAGRASS", "海草");
        putToken("KELP", "海带");
        putToken("DRIED", "干");
        putToken("CACTUS", "仙人掌");
        putToken("SUGAR", "糖");
        putToken("CANE", "蔗");
        putToken("BAMBOO", "竹子");
        putToken("VINE", "藤蔓");
        putToken("LILY", "百合");
        putToken("PAD", "叶");
        putToken("ROSE", "玫瑰");
        putToken("BUSH", "丛");
        putToken("FLOWER", "花");
        putToken("TORCHFLOWER", "火把花");
        putToken("PITCHER", "瓶子草");
        putToken("SPORE", "孢子");
        putToken("BLOSSOM", "花");
        putToken("PROPAGULE", "胎生苗");

        // 农作物 / 食物
        putToken("WHEAT", "小麦");
        putToken("BEETROOT", "甜菜");
        putToken("CARROT", "胡萝卜");
        putToken("POTATO", "马铃薯");
        putToken("MELON", "西瓜");
        putToken("PUMPKIN", "南瓜");
        putToken("SWEET", "甜");
        putToken("GLOW", "发光");
        putToken("COCOA", "可可");
        putToken("BEANS", "豆");
        putToken("NETHER", "下界");
        putToken("WART", "疣");
        putToken("CHORUS", "紫颂");
        putToken("FRUIT", "果");
        putToken("POPPED", "爆");
        putToken("APPLE", "苹果");
        putToken("GOLDEN", "金");
        putToken("ENCHANTED", "附魔");
        putToken("BREAD", "面包");
        putToken("COOKIE", "曲奇");
        putToken("CAKE", "蛋糕");
        putToken("PIE", "派");
        putToken("RABBIT", "兔");
        putToken("STEW", "煲");
        putToken("SUSPICIOUS", "谜之");
        putToken("HONEY", "蜂蜜");
        putToken("COMB", "蜜脾");
        putToken("BOTTLE", "瓶");
        putToken("MILK", "奶");
        putToken("BEEF", "牛肉");
        putToken("PORKCHOP", "猪排");
        putToken("MUTTON", "羊肉");
        putToken("CHICKEN", "鸡肉");
        putToken("COD", "鳕鱼");
        putToken("SALMON", "鲑鱼");
        putToken("TROPICAL", "热带");
        putToken("FISH", "鱼");
        putToken("PUFFERFISH", "河豚");
        putToken("KELP", "海带");
        putToken("DRIED", "干");
        putToken("ROTTEN", "腐烂");
        putToken("SPIDER", "蜘蛛");
        putToken("EYE", "眼");
        putToken("FERMENTED", "发酵");
        putToken("BLAZE", "烈焰");
        putToken("GHAST", "恶魂");
        putToken("TEAR", "泪");
        putToken("MAGMA", "岩浆");
        putToken("CREAM", "膏");
        putToken("PHANTOM", "幻翼");
        putToken("MEMBRANE", "膜");

        // 矿物 / 材料
        putToken("COAL", "煤炭");
        putToken("CHARCOAL", "木炭");
        putToken("IRON", "铁");
        putToken("GOLD", "金");
        putToken("COPPER", "铜");
        putToken("DIAMOND", "钻石");
        putToken("EMERALD", "绿宝石");
        putToken("LAPIS", "青金石");
        putToken("LAZULI", "石");
        putToken("REDSTONE", "红石");
        putToken("NETHERITE", "下界合金");
        putToken("QUARTZ", "石英");
        putToken("PRISMARINE", "海晶");
        putToken("SHARD", "碎片");
        putToken("CRYSTALS", "水晶");
        putToken("BRICK", "砖");
        putToken("NETHER", "下界");
        putToken("STAR", "之星");
        putToken("PEARL", "珍珠");
        putToken("ENDER", "末影");
        putToken("SHULKER", "潜影");
        putToken("SHELL", "壳");
        putToken("NAUTILUS", "鹦鹉螺");
        putToken("HEART", "之心");
        putToken("SEA", "海洋");
        putToken("OF", "之");
        putToken("THE", "");
        putToken("SCUTE", "鳞甲");
        putToken("TURTLE", "海龟");
        putToken("RABBIT", "兔子");
        putToken("FOOT", "脚");
        putToken("LEATHER", "皮革");
        putToken("STRING", "线");
        putToken("FEATHER", "羽毛");
        putToken("FLINT", "燧石");
        putToken("BONE", "骨头");
        putToken("GUNPOWDER", "火药");
        putToken("SLIME", "黏液");
        putToken("BALL", "球");
        putToken("CLAY", "黏土");
        putToken("BRICK", "砖");
        putToken("PAPER", "纸");
        putToken("BOOK", "书");
        putToken("WRITABLE", "书与笔");
        putToken("WRITTEN", "成书");
        putToken("KNOWLEDGE", "知识");
        putToken("EXPERIENCE", "经验");
        putToken("FIREWORK", "烟花");
        putToken("ROCKET", "火箭");
        putToken("STAR", "之星");
        putToken("GLOWSTONE", "荧石");
        putToken("DUST", "粉");
        putToken("BLAZE", "烈焰");
        putToken("ROD", "棒");
        putToken("BREEZE", "旋风");
        putToken("WIND", "风");
        putToken("CHARGE", "弹");
        putToken("HEAVY", "重");
        putToken("WEIGHTED", "加权");
        putToken("LIGHT", "轻");
        putToken("TRIAL", "试炼");
        putToken("KEY", "钥匙");
        putToken("OMINOUS", "不祥");
        putToken("VAULT", "宝库");
        putToken("FLOW", "涡流");
        putToken("ARMADILLO", "犰狳");
        putToken("SCUTE", "鳞甲");
        putToken("WOLF", "狼");
        putToken("ARMOR", "盔甲");
        putToken("TRIM", "纹饰");
        putToken("SMITHING", "锻造");
        putToken("TEMPLATE", "模板");
        putToken("COAST", "海岸");
        putToken("SENTRY", "哨兵");
        putToken("DUNE", "沙丘");
        putToken("WILD", "荒野");
        putToken("RAISER", "牧民");
        putToken("RIB", "肋骨");
        putToken("SNOUT", "猪鼻");
        putToken("TIDE", "潮汐");
        putToken("VEX", "恼鬼");
        putToken("WARD", "监守");
        putToken("WAYFINDER", "向导");
        putToken("SHAPER", "塑造");
        putToken("SILENCE", "幽静");
        putToken("HOST", "雇主");
        putToken("RAGE", "狂怒");
        putToken("SPIRE", "尖塔");
        putToken("EYE", "之眼");
        putToken("TOTEM", "图腾");
        putToken("UNDYING", "不死");
        putToken("BEEF", "牛肉");
        putToken("STEAK", "牛排");
        putToken("PORKCHOP", "猪排");
        putToken("CHICKEN", "鸡肉");
        putToken("MUTTON", "羊肉");
        putToken("RABBIT", "兔肉");
        putToken("COD", "生鳕鱼");
        putToken("SALMON", "生鲑鱼");
        putToken("COOKED", "熟");
        putToken("BEETROOT", "甜菜");
        putToken("SOUP", "汤");

        // 红石 / 机械
        putToken("REDSTONE", "红石");
        putToken("REPEATER", "中继器");
        putToken("COMPARATOR", "比较器");
        putToken("OBSERVER", "侦测器");
        putToken("DISPENSER", "发射器");
        putToken("DROPPER", "投掷器");
        putToken("HOPPER", "漏斗");
        putToken("PISTON", "活塞");
        putToken("STICKY", "黏性");
        putToken("TARGET", "标靶");
        putToken("LEVER", "拉杆");
        putToken("TRIPWIRE", "绊线");
        putToken("HOOK", "钩");
        putToken("DAYLIGHT", "阳光");
        putToken("DETECTOR", "探测");
        putToken("RAIL", "铁轨");
        putToken("POWERED", "动力");
        putToken("ACTIVATOR", "激活");
        putToken("DETECTOR", "探测");
        putToken("TNT", "TNT");
        putToken("NOTE", "音符");
        putToken("JUKEBOX", "唱片机");
        putToken("LECTERN", "讲台");
        putToken("LODESTONE", "磁石");
        putToken("RESPAWN", "重生");
        putToken("ANCHOR", "锚");
        putToken("SCAFFOLDING", "脚手架");
        putToken("BELL", "钟");
        putToken("CAMPFIRE", "营火");
        putToken("SOUL", "灵魂");
        putToken("COMPOSTER", "堆肥桶");
        putToken("BEEHIVE", "蜂箱");
        putToken("BEE", "蜜蜂");
        putToken("NEST", "巢");
        putToken("HONEYCOMB", "蜜脾");
        putToken("DECORATED", "饰纹");
        putToken("POT", "陶罐");
        putToken("SHERD", "碎片");
        putToken("ARCHER", "弓箭");
        putToken("PRIZE", "珍宝");
        putToken("ARMS", "双臂");
        putToken("UP", "举臂");
        putToken("SKULL", "头颅");
        putToken("BLADE", "利刃");
        putToken("BURN", "燃烧");
        putToken("DANGER", "危机");
        putToken("EXPLORER", "探险");
        putToken("FRIEND", "友人");
        putToken("HEART", "爱心");
        putToken("HEARTBREAK", "心碎");
        putToken("HOWL", "嚎叫");
        putToken("MINER", "采矿");
        putToken("MOURNER", "悲恸");
        putToken("PLENTY", "富饶");
        putToken("SHEAF", "麦捆");
        putToken("SNORT", "喷嚏");
        putToken("CREAKING", "嘎吱");
        putToken("HEART", "心");
        putToken("TRIAL", "试炼");
        putToken("SPAWNER", "刷怪笼");
        putToken("MONSTER", "怪物");
        putToken("CHEST", "箱子");
        putToken("TRAPPED", "陷阱");
        putToken("ENDER", "末影");
        putToken("CRYSTAL", "水晶");
        putToken("BEACON", "信标");
        putToken("CONDUIT", "潮涌");
        putToken("DRAGON", "龙");
        putToken("EGG", "蛋");
        putToken("ELYTRA", "鞘翅");
        putToken("FIREWORK", "烟花");
        putToken("FILLED", "装有");
        putToken("MAP", "地图");
        putToken("EMPTY", "空");
        putToken("LOCATOR", "定位");
        putToken("CARROT", "胡萝卜");
        putToken("ON", "上");
        putToken("A", "");
        putToken("STICK", "木棍");
        putToken("BOWL", "碗");
        putToken("MUSHROOM", "蘑菇");
        putToken("STEW", "煲");
        putToken("RABBIT", "兔");
        putToken("FOOT", "脚");
        putToken("BEETROOT", "甜菜");
        putToken("SUSPICIOUS", "谜之");
        putToken("STEW", "炖菜");
        putToken("GLASS", "玻璃");
        putToken("BOTTLE", "瓶");
        putToken("DRAGON", "龙");
        putToken("BREATH", "之息");
        putToken("POTION", "药水");
        putToken("SPLASH", "喷溅");
        putToken("LINGERING", "滞留");
        putToken("TIPPED", "药箭");
        putToken("ARROW", "箭");
        putToken("SPECTRAL", "光灵");
        putToken("SHIELD", "盾牌");
        putToken("BANNER", "旗帜");
        putToken("PATTERN", "图案");
        putToken("CREEPER", "苦力怕");
        putToken("SKULL", "头颅");
        putToken("FLOWER", "花朵");
        putToken("GLOBE", "地球");
        putToken("PIGLIN", "猪灵");
        putToken("MOJANG", "Mojang");
        putToken("FIELD", "田野");
        putToken("MASONED", "砖纹");
        putToken("BORDURE", "波纹");
        putToken("FISH", "鱼");
        putToken("CROSS", "十字");
        putToken("TRIANGLE", "三角");
        putToken("STRIPE", "条纹");
        putToken("BOTTOM", "底");
        putToken("TOP", "顶");
        putToken("CENTER", "中");
        putToken("MIDDLE", "中");
        putToken("RIGHT", "右");
        putToken("LEFT", "左");
        putToken("CURVED", "弯曲");
        putToken("CRESCENT", "新月");
        putToken("FLOWER", "花");
        putToken("HALF", "半");
        putToken("HORIZONTAL", "横");
        putToken("VERTICAL", "竖");
        putToken("SMALL", "小");
        putToken("SQUARE", "方形");
        putToken("STRAIGHT", "直");
        putToken("CROSS", "交叉");
        putToken("GRADIENT", "渐变");
        putToken("UP", "上");
        putToken("DOWN", "下");
        putToken("BRICKS", "砖");
        putToken("GUSTER", "旋风");
        putToken("BOLT", "螺栓");
        putToken("FLOW", "涡流");
        putToken("ARMOR", "盔甲");
        putToken("TRIM", "纹饰");
        putToken("COAST", "海岸");
        putToken("DUNE", "沙丘");
        putToken("EYE", "之眼");
        putToken("RIB", "肋骨");
        putToken("SENTRY", "哨兵");
        putToken("SNOUT", "猪鼻");
        putToken("SPIRE", "尖塔");
        putToken("TIDE", "潮汐");
        putToken("VEX", "恼鬼");
        putToken("WARD", "监守");
        putToken("WAYFINDER", "向导");
        putToken("WILD", "荒野");
        putToken("RAISER", "牧民");
        putToken("SHAPER", "塑造");
        putToken("SILENCE", "幽静");
        putToken("HOST", "雇主");
        putToken("RAGE", "狂怒");
        putToken("SPIRE", "尖塔");
        putToken("NETHER", "下界");
        putToken("WART", "疣");
        putToken("SHROOMLIGHT", "菌光体");
        putToken("SOUL", "灵魂");
        putToken("SOIL", "土");
        putToken("FROGLIGHT", "蛙明灯");
        putToken("PEARLESCENT", "珠光");
        putToken("VERDANT", "苍翠");
        putToken("OCHRE", "赭黄");
        putToken("MANGROVE", "红树");
        putToken("ROOT", "根");
        putToken("MUDDY", "泥泞");
        putToken("PACKED", "压实");
        putToken("REINFORCED", "强化");
        putToken("CHAIN", "锁链");
        putToken("GLOW", "荧光");
        putToken("ITEM", "物品");
        putToken("FRAME", "展示框");
        putToken("FLOW", "涡流");
        putToken("POWDER", "粉末");
        putToken("SNOW", "雪");
        putToken("BALL", "球");
        putToken("POWDER", "粉末");
        putToken("SNOW", "雪");
        putToken("BUCKET", "桶");
        putToken("AXOLOTL", "美西螈");
        putToken("TADPOLE", "蝌蚪");
        putToken("COD", "鳕鱼");
        putToken("SALMON", "鲑鱼");
        putToken("PUFFERFISH", "河豚");
        putToken("TROPICAL", "热带");
        putToken("FISH", "鱼");
        putToken("AXOLOTL", "美西螈");
        putToken("TADPOLE", "蝌蚪");
        putToken("LLAMA", "羊驼");
        putToken("DONKEY", "驴");
        putToken("MULE", "骡");
        putToken("HORSE", "马");
        putToken("SKELETON", "骷髅");
        putToken("ZOMBIE", "僵尸");
        putToken("SPAWN", "生成");
        putToken("VILLAGER", "村民");
        putToken("WANDERING", "流浪");
        putToken("TRADER", "商人");
        putToken("IRON", "铁");
        putToken("GOLD", "金");
        putToken("DIAMOND", "钻石");
        putToken("NETHERITE", "下界合金");
        putToken("LEATHER", "皮革");
        putToken("TURTLE", "海龟");
        putToken("SCUTE", "鳞甲");
        putToken("WOLF", "狼");
        putToken("ARMOR", "盔甲");
        putToken("TRIM", "纹饰");
        putToken("SMITHING", "锻造");
        putToken("TEMPLATE", "模板");
        putToken("COAST", "海岸");
        putToken("SENTRY", "哨兵");
        putToken("DUNE", "沙丘");
        putToken("WILD", "荒野");
        putToken("RAISER", "牧民");
        putToken("RIB", "肋骨");
        putToken("SNOUT", "猪鼻");
        putToken("TIDE", "潮汐");
        putToken("VEX", "恼鬼");
        putToken("HAY", "干草");
        putToken("TARGET", "标靶");
        putToken("FLESH", "肉");
        putToken("LEAD", "拴绳");
        putToken("SADDLE", "鞍");
        putToken("VALLEY", "谷");
        putToken("SPEED", "速度");
    }

    private static void putToken(String key, String value) {
        TOKENS.put(key, value);
    }

    private static void putSuffix(String key, String value) {
        SUFFIXES.put(key, value);
    }
}
